### ISSUE TITLE
api/* urls return 403 (Forbidden) when user is logged in via /api/admin

### ISSUE THREAD

**Issue by Photoshopper** [gtalarico/django-vue-template#13]
When I log in via /api/admin Django creates "sessionid" cookie and I'm not able to use "Messages example" as it becames broken because of 403 error. I tried to set REST_SESSION_LOGIN = False but it didn't help. How to solve this?

**Comment by gtalarico** [comment]
I am not sure what the issue is or how to help without additional details:
* Link to "Message example"
* Sample code / repo link?
* or [MCRE](https://stackoverflow.com/help/mcve)

**Comment by Photoshopper** [comment]
Please check this video https://www.useloom.com/share/e1d134cd00c24f3eb2afcd361c4df015
The problem is out of the box. I didn't change anything

**Comment by gtalarico** [comment]
Thanks for the video. Not sure what the issue is but I will look into it.

### Expected Outcome
Messages can be added and deleted (ie. server requests go through without errors)

### Actual Outcome
If user is logged in the Django Admin panel, all requests to server return a 403 error

### Steps to reproduce
* Start dev servers for backend and client
* Send and delete messages > work as expected
* Go to `/admin` and login.
* Go back and try adding/deleting new messages
* **requests fail with 403 error**
* Logout the admin panel
* Send and delete messages
* **requests work as expected**

PS: @Photoshopper If I may suggest, a format like this ☝️ help communicate the issue more effectively

**Comment by chaineater** [comment]
is this fix?

**Comment by lclarkdwain** [comment]
setting X-CSRFToken at header solved this since it should match with csrftoken in cookies, I submit pr instead for this. 

It's my first time submitting but I hope it's not a bother, thanks.

**Comment by gtalarico** [comment]
Merged. Thanks!
