### ISSUE TITLE
yarn serve doesn't refresh django app

### ISSUE THREAD

**Issue by dustinmichels** [gtalarico/django-vue-template#21]
Hi! I like this template *a lot*.

One question / issue.

I start two servers, as recommended in the README

```bash
python manage.py runserver
yarn serve  # in another tab
```

When I edit the JavaScript, it looks like the files are re-compiled, but I don't see any changes in the Django app. It seems like the Django app is just serving the js in the `dist/` directory, and the whatever files vue is re-compiling are held in memory, not written to that `dist/` directory.

It seems like the intention with the project is that if both servers are running at the same time you can edit the JS and Django will serve the re-loaded files. Is that correct? Am I missing something, or is this an error in this code?

**Comment by gtalarico** [comment]
Hi!

`dist/` is only served by django in production.
During dev, static files (html, css + js build) are served directly from memory by yarn/webpack on `8080` (dist will not change) and the api is served by django on `8000`

note vueconfig is setup so the front end app will call :8000 for the api.

This setups allows auto reload on both sides - yarn auto reloads and hot module reload on any html/js change, and django reload code on any change on the api side.

For prod, since you want to serve the production build, 
you build the js app using `yarn build` which will created/update `dist/` and then have django will served that

ie. during dev use localhost:8080 and your front will auto reload

**Comment by dustinmichels** [comment]
I see. Looks like my issue is that I was looking at :8000 instead of :8080. Both pages look the same, except :8000 doesn't reload the JavaScript. Thanks!

**Comment by gtalarico** [comment]
Awesome. Thanks for the uptade.
