### ISSUE TITLE
http://localhost:8080/sockjs-node errors

### ISSUE THREAD

**Issue by devzero0** [gtalarico/django-vue-template#5]
First off, thanks for the great template. The browser console reports errors trying to connect to http://localhost:8080/sockjs-node/..., because the dev server isn't listening on localhost but instead the host IP. How do you change the development server to listen on localhost as well? I tried setting "host:'localhost'" in vue.config.js but it is ignored. Alternately, how do you point those sockjs-node calls to the hostname rather than localhost?

**Comment by gtalarico** [comment]
I usually only get the socket error when the devserver is not running or has tripped on an exception, so I am not sure I fully understand the issue.

Here is the setup I use:
`python manage.py runserver` Serves django on default: `127.0.0.1:8000`
`yarn serve` serves webpack dev server on default `localhost:8080`

Vue backend calls go to `/api/*`, and dev server proxies that to `localhost:8000`.
since `localhost` usually == `127.0.0.1` Django is able to answer those requests. See below.

![image](https://user-images.githubusercontent.com/9513968/44998579-c591a300-af84-11e8-9f8f-12136c9d0dd2.png)

If this setup doesn't work for you, you can try adding host up (`127.0.0.1`) to your dev server config instead:

# Dev Server config
```
    devServer: {
      proxy: {
        '/api*': {
          // Forward frontend dev server request for /api to django dev server
          // target: 'http://localhost:8000/',  // This one works as wel since 127.0.0.1 == localhost for me.
          target: 'http://127.0.0.1:8000/',  // <- django's default
        }
      }
    }
```

For consistency's sake, maybe we can change settings to have all on the same host 
(I kept the default ones to reduce modifications to default settings).

We could serve Django on localhost by using `python manage.py runserver localhost:8000` or change the webpack config to serve on `127.0.0.1`

Does this answer your question?

**Comment by devzero0** [comment]
Thanks for the quick and detailed response. I do have Django listening on 0.0.0.0:8000, but the queries for sockjs-node are going against localhost:8080 and for some reason the webpack dev server isn't listening on localhost. Included are screenshots of "yarn serve" and from the Chrome console showing the failing requests (zaphod is my workstation name). Can you suggest the configuration change to make my "yarn serve" look like yours? 
<img width="485" alt="screen shot 2018-09-03 at 5 19 29 pm" src="https://user-images.githubusercontent.com/7071188/45001717-90457f00-af9d-11e8-8ea0-e2590e38335a.png">
<img width="615" alt="screen shot 2018-09-03 at 5 20 00 pm" src="https://user-images.githubusercontent.com/7071188/45001726-9dfb0480-af9d-11e8-823a-9fcb4628f4c9.png">

**Comment by gtalarico** [comment]
You can modify your package.json to select a specific hostname or port.
https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve

![image](https://user-images.githubusercontent.com/9513968/45001852-e2d36b00-af9e-11e8-9283-b2ddbb49ae91.png)
![image](https://user-images.githubusercontent.com/9513968/45001863-f979c200-af9e-11e8-89e1-5b6841243f47.png)

**Comment by devzero0** [comment]
Was just typing up this response when I saw yours come in. Thanks again for your help. 

-------------------------------------------------------------------------
Looks like I got it working. I added "-- host 0.0.0.0" to the line in package.json that specifies the "serve" script and now it it is listening on both localhost and my host's IP. I also had to add "disableHostCheck: true" to the devServer vue.config.js to resolve "Invalid Host header" errors.

**Comment by gtalarico** [comment]
`disableHostCheck: true` not sure I would do this for production, but for dev should be ok, although I have not needed with the setup I described above.
Anyhow, glad you got it working!

**Comment by AmeliaCult** [comment]
HI @gtalarico !

I have a big problem with my game server, I am reading and trying since weeks but it does not want to be reachable from internet.

The server includes 3 applications:
1. Proxy (for the game connection)
2. Core (for listening ports and interact with the webserver)
3. Webserver (built with "npm run build")

I would really appreciate if someone could help me with the configuration  because I am not a programmer and i have no idea about those languages
